version: "3"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - wordpress-files:/srv
  wordpress:
    build: ./wordpress
    container_name: wordpress
    env_file: .env
    restart: on-failure
    volumes:
      - wordpress-files:/srv
  mariadb:
    build: ./mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - wordpress-database:/var/lib/mysql/wordpress
volumes:
  wordpress-files:
  wordpress-database:
