version: "3"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress-files:/srv
  wordpress:
    build: ./wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: .env
    restart: on-failure
    volumes:
      - wordpress-files:/srv
  mariadb:
    build: ./mariadb
    container_name: mariadb
    env_file: .env
    restart: on-failure
    volumes:
      - wordpress-database:/var/lib/mysql/wordpress
volumes:
  wordpress-files:
  wordpress-database:
